services:
  postgres:
    image: postgres:16
    container_name: cuide-do-pet-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cuidedopet
    volumes:
      - cuide-do-pet-db-data:/var/lib/postgresql/data

volumes:
  cuide-do-pet-db-data:
  